ngrok:
  image: toby1991/ngrok:latest
  expose:
    - "80"
    - "443"
  ports:
    - "4443:4443"
  volumes:
    - /ngrok:/ngrok_data
  environment:
    - DOMAIN="headfile.net"
  command: /bin/sh /server.sh
